export enum ResponseCode {
  REQUEST_TIMEOUT = 'REQUEST_TIMEOUT',
  INVALID_PARAMETER_VALUE = 'INVALID_PARAMETER_VALUE',
  DUPLICATE_REQUEST = 'DUPLICATE_REQUEST',
  SUCCESS = 'SUCCESS',
  DATA_NOT_EXISTS = 'DATA_NOT_EXISTS',
  MISS_REQUIRED_PARAMETER = 'MISS_REQUIRED_PARAMETER',
  AUTH_ACCESS_DENIED = 'AUTH_ACCESS_DENIED',
  PARAMS_IS_EMPTY = 'PARAMS_IS_EMPTY',
  FAILURE = 'FAILURE',
  RATELIMITED = 'RATELIMITED',
  SYSTEM_IS_BUSY = 'SYSTEM_IS_BUSY',
  ILLEGAL_ARGUMENT = 'ILLEGAL_ARGUMENT',
  ILLEGAL_REQUEST = 'ILLEGAL_REQUEST',
  DEGRADATION = 'DEGRADATION',
  INVALID_PARAMS_LENGTH = 'INVALID_PARAMS_LENGTH',
}
//generate by interpret-cli dubbo2.js
