export default class JoiKeys {
  //https://hapi.dev/family/joi/?v=15.1.1#any
  private static keys: string[] = [
    //any
    'allow',
    'valid',
    'invalid',
    'required',
    'optional',
    'forbidden',
    'strip',
    'description',
    'notes',
    'tags',
    'meta',
    'example',
    'unit',
    'options',
    'strict',
    'default',
    'concat',
    'when',
    'label',
    'raw',
    'empty',
    'error',
    'describe',
    //array
    'sparse',
    'single',
    'items',
    'ordered',
    'min',
    'max',
    'length',
    'unique',
    'has',
    //boolean
    'truthy',
    'falsy',
    'insensitive',
    //binary
    'encoding',
    'min',
    'max',
    'length',
    //date
    'min',
    'max',
    'greater',
    'less',
    'iso',
    'timestamp',
    //func
    'arity',
    'minArity',
    'maxArity',
    'class',
    'ref',
    //number
    'unsafe',
    'min',
    'max',
    'greater',
    'less',
    'integer',
    'precision',
    'multiple',
    'positive',
    'negative',
    'port',
    //objext
    'keys',
    'append',
    //以后补充
  ];

  public static in(key: string) {
    if (this.keys.includes(key)) return true;
  }
}
